"""Generate the README's list of entries from the entries themselves.

A hand-kept list drifts: the README once said every entry ran in both languages after six had become
R only. So the list lives between two markers in README.md and is written from each entry's
meta.json. `--check` compares instead of writing and exits 1 when the committed README is stale,
which CI runs, so adding, renaming or changing an entry's engines without regenerating fails the
build rather than leaving the README wrong.

Usage:
    python harness/catalogue.py           # rewrite the block in README.md
    python harness/catalogue.py --check   # exit 1 if README.md is not what this would write
"""

import argparse
import json
import sys
from pathlib import Path

START = "<!-- catalogue:start (generated by harness/catalogue.py; do not edit by hand) -->"
END = "<!-- catalogue:end -->"

# The engine states harness/metadata.py accepts, and no others. An unknown one stops generation
# rather than being rendered as the nearest familiar phrase, because each is a different claim.
ENGINE_STATES = ("executed", "not-executed", "not-applicable")
LANG_NAMES = {"r": "R", "python": "Python"}


def entries(lib):
    out = []
    for meta_path in sorted(Path(lib).glob("*/meta.json")):
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        engines = meta.get("engines") or {}
        ran, unrun = [], []
        for lang in ("r", "python"):
            state = engines.get(lang)
            if state not in ENGINE_STATES:
                raise SystemExit(f"{meta_path}: engine {lang!r} has unknown state {state!r}")
            if state == "executed":
                ran.append(LANG_NAMES[lang])
            elif state == "not-executed":
                unrun.append(LANG_NAMES[lang])
        out.append({"id": meta["id"], "title": meta["title"], "ran": ran, "unrun": unrun})
    if not out:
        raise SystemExit(f"no entries found under {lib}")
    return out


def executed_cell(e):
    """What CI runs, and nothing else. A file that exists but is not run is named as such, so a
    reader cannot take its presence for verification."""
    cell = " and ".join(e["ran"]) if e["ran"] else "not executed"
    if e["unrun"]:
        cell += " (" + " and ".join(e["unrun"]) + " present, not run)"
    return cell


def render(lib):
    rows = entries(lib)
    both = sum(1 for e in rows if len(e["ran"]) == 2)
    one = sum(1 for e in rows if len(e["ran"]) == 1)
    none = len(rows) - both - one
    summary = (f"**{len(rows)} entries.** {both} are executed in both R and Python and carry both "
               f"claims; {one} are executed in one language and carry the recovery claim alone, "
               "with the reason in the entry's `meta.json`.")
    if none:
        summary += f" {none} are not executed and carry neither claim."
    lines = [
        START,
        "",
        summary,
        "",
        "| Entry | What it estimates | Executed in |",
        "|---|---|---|",
    ]
    for e in sorted(rows, key=lambda e: e["id"]):
        lines.append(f"| [`{e['id']}`](lib/{e['id']}/) | {e['title']} | {executed_cell(e)} |")
    lines += ["", END]
    return "\n".join(lines)


def splice(readme_text, block):
    if readme_text.count(START) != 1 or readme_text.count(END) != 1:
        raise SystemExit("README.md must contain each catalogue marker exactly once")
    head, rest = readme_text.split(START)
    _, tail = rest.split(END)
    return head + block + tail


def main(argv=None):
    here = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--readme", default=str(here / "README.md"))
    ap.add_argument("--lib", default=str(here / "lib"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    readme = Path(args.readme)
    current = readme.read_text(encoding="utf-8")
    wanted = splice(current, render(args.lib))
    if args.check:
        if current != wanted:
            print("  FAIL README.md's list of entries is stale; run python harness/catalogue.py")
            return 1
        print("  README.md's list of entries matches lib/")
        return 0
    readme.write_text(wanted, encoding="utf-8")
    print("README.md list of entries written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
