"""Generate the README's list of entries from the entries themselves.

A hand-kept list drifts: the README once said every entry ran in both languages after six had become
R only. So the list lives between two markers in README.md and is written from each entry's
meta.json. `--check` compares instead of writing and exits 1 when the committed README is stale,
which CI runs, so adding, renaming or changing an entry's engines without regenerating fails the
build rather than leaving the README wrong.

Usage:
    python harness/catalogue.py           # rewrite the block in README.md
    python harness/catalogue.py --check   # exit 1 if README.md is not what this would write
"""

import argparse
import json
import sys
from pathlib import Path

START = "<!-- catalogue:start (generated by harness/catalogue.py; do not edit by hand) -->"
END = "<!-- catalogue:end -->"

# The only engine states the harness knows. An unknown one stops generation rather than being
# rendered as the nearest familiar phrase, because each is a different claim to a reader.
ENGINE_WORDS = {"executed": True, "not-applicable": False}


def entries(lib):
    out = []
    for meta_path in sorted(Path(lib).glob("*/meta.json")):
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        engines = meta.get("engines") or {}
        ran = []
        for lang in ("r", "python"):
            state = engines.get(lang)
            if state not in ENGINE_WORDS:
                raise SystemExit(f"{meta_path}: engine {lang!r} has unknown state {state!r}")
            if ENGINE_WORDS[state]:
                ran.append({"r": "R", "python": "Python"}[lang])
        if not ran:
            raise SystemExit(f"{meta_path}: no engine is executed")
        out.append({"id": meta["id"], "title": meta["title"], "ran": ran})
    if not out:
        raise SystemExit(f"no entries found under {lib}")
    return out


def render(lib):
    rows = entries(lib)
    both = sum(1 for e in rows if len(e["ran"]) == 2)
    lines = [
        START,
        "",
        f"**{len(rows)} entries.** {both} run in both R and Python and carry both claims; "
        f"{len(rows) - both} run in R only and carry the recovery claim alone, with the reason in "
        "the entry's `meta.json`.",
        "",
        "| Entry | What it estimates | Executed in |",
        "|---|---|---|",
    ]
    for e in sorted(rows, key=lambda e: e["id"]):
        lines.append(f"| [`{e['id']}`](lib/{e['id']}/) | {e['title']} | {' and '.join(e['ran'])} |")
    lines += ["", END]
    return "\n".join(lines)


def splice(readme_text, block):
    if readme_text.count(START) != 1 or readme_text.count(END) != 1:
        raise SystemExit("README.md must contain each catalogue marker exactly once")
    head, rest = readme_text.split(START)
    _, tail = rest.split(END)
    return head + block + tail


def main(argv=None):
    here = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--readme", default=str(here / "README.md"))
    ap.add_argument("--lib", default=str(here / "lib"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    readme = Path(args.readme)
    current = readme.read_text(encoding="utf-8")
    wanted = splice(current, render(args.lib))
    if args.check:
        if current != wanted:
            print("  FAIL README.md's list of entries is stale; run python harness/catalogue.py")
            return 1
        print("  README.md's list of entries matches lib/")
        return 0
    readme.write_text(wanted, encoding="utf-8")
    print("README.md list of entries written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
